language: go
go:
- 1.8.x
notifications:
  email: false
install:
- true
script:
- "./script/build"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ua6dIWkA+aPOSz12s1ZeQoGrNC3ijVB4xodz0zcYsRTKl0EYLXVUSrSs1IzQq2sqhm5lYL4cVsqCs+oZCqRyQo2a+uftsAl5f5n3BmGxCZKhOXONQ1Dyt9zx1gNUPK+huySeQ0Yo11ZfIU6TkvLU3cILzMoIHJs8enaBp2xmqkYRSTUsbuT9KYzSjn9aUpihePlkXS/doqxMIjAhTTCiFErHX9cPhyovW3FfMcLFQpk8xmpDqk3yqqfoObHiywfGHY7kwRry3cxk+gQgmCuCYSrH4DC7nvlAIlKX4NjLD5tkCfr/6RMy/Wg2s2gTPWhcRosh2VPDZoIIqwdjdxnRzb4Opw1OAt7k54CCz8RBxrcs6P+HCYMWU5oUQDnGP//QiOQPfoo02eAKU6Qp3A6SizLkWHgemANWk04i6oLQcdpdeZlAgLJm8fLAVOyj+ISyktFdvuFVxzmHLZdx6cO3V7gkEGDD8wxQQbg79mHT0AJK4iTurenysB24UyPxyyYkbCFAD125Nd6L3KZDWIn9upbhrhLBcRnFJog7xVMVbuznrONPoaCRIvMOhUmCW0ptRtE056p1Rkd84Hoso052AloVtGcIIIpRfc+Ki2iPDzmXorLxqGlz0QmBtzrhIxL61hnVwO5JOOKxxS2LlYt+R6Kb9bGiYX0wU27EbdY/tZM=
  file: 
    - kube-log-tail.linux.amd64
    - kube-log-tail.darwin.amd64
  on:
    repo: bakins/kube-log-tail
    tags: true
