[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "85ace5365f33b16fc735c866a12e3c765b9700f2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "3.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

  